### PR TITLE
Update LINGUAS

### PR DESCRIPTION
**Pull request by safak45x**
tr(Turkish) add pls

### CODE REVIEW

**Comment by rajkumaar23** [comment]
@safak45x Are you planning to add the Turkish translations for **badgie** ?

**Comment by safak45x** [comment]
> @safak45x Are you planning to add the Turkish translations for **badgie** ?

[tr.po.zip](https://github.com/rajkumaar23/badgie/files/5285342/tr.po.zip)
yes I translated
I hope you add

**Comment by rajkumaar23** [comment]
@safak45x You need to add translations to the app like this PR - https://github.com/rajkumaar23/badgie/pull/22

**Comment by safak45x** [comment]
If you add
Translation files available

**Comment by safak45x** [comment]
> @safak45x You need to add translations to the app like this PR - #22

okey

**Pull request closed without merging**
